"""EXT-018: gated-thinking on the repo code grain (--think flag).

Unit tests — all offline. No Jetson, no subprocess, no repo checkout.
Patches: _load_agent_from_file (agents), jaros_solve_ops.run_tests (Docker),
         harness.pass1_eval._doctest_asserts + _visible_ok (gate helpers),
         harness.commit_replay._g_code_think (think-regeneration stub).

Coverage:
  (a) think=True + current_src has examples + direct code FAILS them
       -> _g_code_think called exactly once, returned code used
  (b) think=True + current_src has examples + direct code PASSES them
       -> _g_code_think NOT called (gate kept direct)
  (c) think=True + current_src has NO examples
       -> _g_code_think NOT called (nothing to gate on)
  (d) think=False (default) + examples that would fail
       -> _g_code_think NOT called (default path byte-identical)
  (e) ast.parse + import smoke on behavioral_solve.py
  (f) _g_code_think defined in commit_replay with correct signature
"""
from __future__ import annotations

import ast
import sys
import uuid
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# ---------------------------------------------------------------------------
# Stub LLM (never called in these tests — agents are patched out entirely)
# ---------------------------------------------------------------------------

class _FakeCompletion:
    def __init__(self, text: str = "") -> None:
        self.text = text


class _FakeLlm:
    def complete(self, request) -> _FakeCompletion:
        return _FakeCompletion("def stub():\n    pass\n")


# ---------------------------------------------------------------------------
# Fake agent factory — emits a code.write_file Decision with fixed content
# ---------------------------------------------------------------------------

def _make_stub_agent(content: str, path_key: str = "code_path"):
    from jaros.core import create_decision

    class _StubAgent:
        def decide(self, ctx) -> list:
            path = (ctx.get("spec_path") or ctx.get("test_path")
                    or ctx.get("code_path") or ".jcode/stub.out")
            return [create_decision(
                id=f"stub-{uuid.uuid4().hex}", source="stub-agent",
                type="code.write_file",
                payload={"path": path, "content": content},
            )]
    return _StubAgent()


# The direct code generated by the first code_agent call.
_DIRECT_CODE = "def foo(x):\n    return x + 1\n"
# The think-regenerated code (what _g_code_think returns in the "fires" case).
_THINK_CODE  = "def foo(x):\n    return x\n"

# A parent_src with a docstring example (used when testing with examples).
_PARENT_WITH_EXAMPLES = (
    "def foo(x):\n"
    "    '''Return x.\n"
    "    >>> foo(0)\n"
    "    0\n"
    "    '''\n"
    "    return x\n"
)

# A parent_src with NO docstring examples.
_PARENT_NO_EXAMPLES = "def foo(x):\n    return x\n"


# ---------------------------------------------------------------------------
# Runtime factory
# ---------------------------------------------------------------------------

def _make_runtime(tmp_path: Path):
    from harness.coding_loop import Runtime
    return Runtime(data_dir=tmp_path)


# ---------------------------------------------------------------------------
# Shared agent index: gherkin=0, test=1, code=2
# ---------------------------------------------------------------------------

def _agent_sequence(tmp_path: Path):
    """Return [gherkin_agent, test_agent, code_agent] stubs."""
    spec_p = str(tmp_path / "spec.gherkin")
    test_p = str(tmp_path / "test_foo.py")
    code_p = str(tmp_path / "foo.py")
    gherkin_a = _make_stub_agent("1. Given foo(0) returns 0\n")
    test_a    = _make_stub_agent("from pkg import foo\ndef test_it():\n    assert foo(0)==0\n")
    code_a    = _make_stub_agent(_DIRECT_CODE)
    return [gherkin_a, test_a, code_a], spec_p, test_p, code_p


def _make_load_agent(agents: list):
    idx = [0]
    def _load(filepath, llm):
        a = agents[idx[0] % len(agents)]
        idx[0] += 1
        return a
    return _load


def _make_run_tests_ok():
    """Fake run_tests that always returns exit 0."""
    from jaros.core import create_decision

    def _rt(rt_, command, *, cwd=None, timeout_s=15, source=""):
        d = create_decision(
            id=f"sh-{uuid.uuid4().hex}", source="test",
            type="shell.exec",
            payload={"command": command},
        )
        res = rt_.apply(d)
        if isinstance(res, dict):
            res["exitCode"] = 0
        return res if isinstance(res, dict) else {"exitCode": 0, "stdout": "1 passed", "stderr": ""}
    return _rt


# ---------------------------------------------------------------------------
# (e) Structural smoke
# ---------------------------------------------------------------------------

def test_behavioral_solve_file_parses():
    src = (_REPO_ROOT / "harness" / "behavioral_solve.py").read_text(encoding="utf-8")
    ast.parse(src)  # SyntaxError if broken


def test_commit_replay_file_parses():
    src = (_REPO_ROOT / "harness" / "commit_replay.py").read_text(encoding="utf-8")
    ast.parse(src)


# ---------------------------------------------------------------------------
# (f) _g_code_think is defined and callable
# ---------------------------------------------------------------------------

def test_g_code_think_defined():
    src = (_REPO_ROOT / "harness" / "commit_replay.py").read_text(encoding="utf-8")
    assert "def _g_code_think(" in src, "_g_code_think must be defined in commit_replay.py"


def test_g_code_think_has_think_annotation():
    """_g_code_think prompt must contain <think> instruction."""
    src = (_REPO_ROOT / "harness" / "commit_replay.py").read_text(encoding="utf-8")
    # Find the function body
    start = src.index("def _g_code_think(")
    end = src.index("\ndef ", start + 1)
    body = src[start:end]
    assert "<think>" in body, "_g_code_think prompt must include <think> instruction"
    assert "</think>" in body, "_g_code_think prompt must reference </think>"


# ---------------------------------------------------------------------------
# (a) think=True + examples + direct fails -> think fires
# ---------------------------------------------------------------------------

def test_think_fires_when_examples_fail(tmp_path: Path):
    """Gate: examples exist AND direct code fails them -> _g_code_think called once."""
    from harness.behavioral_solve import behavioral_solve_jaros
    import harness.jaros_solve_ops as _ops

    agents, spec_p, test_p, code_p = _agent_sequence(tmp_path)
    rt = _make_runtime(tmp_path)

    think_call_args = []

    def _fake_g_code_think(subject, name, parent_src, context, gherkin):
        think_call_args.append((subject, name))
        return _THINK_CODE

    with patch("harness.behavioral_solve._load_agent_from_file",
               side_effect=_make_load_agent(agents)), \
         patch.object(_ops, "run_tests", side_effect=_make_run_tests_ok()), \
         patch("harness.pass1_eval._doctest_asserts",
               return_value=[("foo(0)", "0")]), \
         patch("harness.pass1_eval._visible_ok",
               return_value=False), \
         patch("harness.commit_replay._g_code_think",
               side_effect=_fake_g_code_think) as mock_think:

        result = behavioral_solve_jaros(
            intent="implement foo",
            name="foo",
            current_src=_PARENT_WITH_EXAMPLES,
            context="",
            pkg="pkg",
            runtime=rt,
            llm=_FakeLlm(),
            spec_path=spec_p,
            test_path=test_p,
            code_path=code_p,
            think=True,
        )

    # _g_code_think must have been called exactly once
    assert mock_think.call_count == 1, (
        f"Expected _g_code_think to be called once; got {mock_think.call_count}"
    )
    # The result code must be the think-regenerated code
    assert result["code"] == _THINK_CODE, (
        f"Expected think-regenerated code; got {result['code']!r}"
    )


# ---------------------------------------------------------------------------
# (b) think=True + examples + direct PASSES -> think NOT fired
# ---------------------------------------------------------------------------

def test_think_not_fired_when_examples_pass(tmp_path: Path):
    """Gate passes: direct code satisfies examples -> no think call."""
    from harness.behavioral_solve import behavioral_solve_jaros
    import harness.jaros_solve_ops as _ops

    agents, spec_p, test_p, code_p = _agent_sequence(tmp_path)
    rt = _make_runtime(tmp_path)

    with patch("harness.behavioral_solve._load_agent_from_file",
               side_effect=_make_load_agent(agents)), \
         patch.object(_ops, "run_tests", side_effect=_make_run_tests_ok()), \
         patch("harness.pass1_eval._doctest_asserts",
               return_value=[("foo(0)", "0")]), \
         patch("harness.pass1_eval._visible_ok",
               return_value=True), \
         patch("harness.commit_replay._g_code_think") as mock_think:

        result = behavioral_solve_jaros(
            intent="implement foo",
            name="foo",
            current_src=_PARENT_WITH_EXAMPLES,
            context="",
            pkg="pkg",
            runtime=rt,
            llm=_FakeLlm(),
            spec_path=spec_p,
            test_path=test_p,
            code_path=code_p,
            think=True,
        )

    assert mock_think.call_count == 0, (
        f"_g_code_think must NOT be called when direct code passes examples; "
        f"got {mock_think.call_count}"
    )
    # Direct code is kept
    assert result["code"] == _DIRECT_CODE, (
        f"Expected direct code to be kept; got {result['code']!r}"
    )


# ---------------------------------------------------------------------------
# (c) think=True + NO examples -> think NOT fired
# ---------------------------------------------------------------------------

def test_think_not_fired_when_no_examples(tmp_path: Path):
    """No docstring examples -> gate skips, _g_code_think never called."""
    from harness.behavioral_solve import behavioral_solve_jaros
    import harness.jaros_solve_ops as _ops

    agents, spec_p, test_p, code_p = _agent_sequence(tmp_path)
    rt = _make_runtime(tmp_path)

    # No docstring examples returned (empty list)
    with patch("harness.behavioral_solve._load_agent_from_file",
               side_effect=_make_load_agent(agents)), \
         patch.object(_ops, "run_tests", side_effect=_make_run_tests_ok()), \
         patch("harness.pass1_eval._doctest_asserts", return_value=[]), \
         patch("harness.pass1_eval._visible_ok", return_value=False), \
         patch("harness.commit_replay._g_code_think") as mock_think:

        result = behavioral_solve_jaros(
            intent="implement foo",
            name="foo",
            current_src=_PARENT_NO_EXAMPLES,
            context="",
            pkg="pkg",
            runtime=rt,
            llm=_FakeLlm(),
            spec_path=spec_p,
            test_path=test_p,
            code_path=code_p,
            think=True,
        )

    assert mock_think.call_count == 0, (
        f"_g_code_think must NOT be called when current_src has no examples; "
        f"got {mock_think.call_count}"
    )


# ---------------------------------------------------------------------------
# (d) think=False (default) + examples that fail -> think NOT fired
# ---------------------------------------------------------------------------

def test_think_not_fired_when_think_false(tmp_path: Path):
    """Default think=False: even if examples exist and fail, _g_code_think never called."""
    from harness.behavioral_solve import behavioral_solve_jaros
    import harness.jaros_solve_ops as _ops

    agents, spec_p, test_p, code_p = _agent_sequence(tmp_path)
    rt = _make_runtime(tmp_path)

    with patch("harness.behavioral_solve._load_agent_from_file",
               side_effect=_make_load_agent(agents)), \
         patch.object(_ops, "run_tests", side_effect=_make_run_tests_ok()), \
         patch("harness.commit_replay._g_code_think") as mock_think:

        # think=False is the default; pass it explicitly to be unambiguous
        result = behavioral_solve_jaros(
            intent="implement foo",
            name="foo",
            current_src=_PARENT_WITH_EXAMPLES,
            context="",
            pkg="pkg",
            runtime=rt,
            llm=_FakeLlm(),
            spec_path=spec_p,
            test_path=test_p,
            code_path=code_p,
            think=False,
        )

    assert mock_think.call_count == 0, (
        f"_g_code_think must NOT be called when think=False; got {mock_think.call_count}"
    )


# ---------------------------------------------------------------------------
# Extra: think=True with current_src=None -> no crash, no think call
# ---------------------------------------------------------------------------

def test_think_no_crash_when_no_current_src(tmp_path: Path):
    """current_src=None (new function) -> _doctest_asserts gets '' -> no examples -> safe."""
    from harness.behavioral_solve import behavioral_solve_jaros
    import harness.jaros_solve_ops as _ops

    agents, spec_p, test_p, code_p = _agent_sequence(tmp_path)
    rt = _make_runtime(tmp_path)

    with patch("harness.behavioral_solve._load_agent_from_file",
               side_effect=_make_load_agent(agents)), \
         patch.object(_ops, "run_tests", side_effect=_make_run_tests_ok()), \
         patch("harness.commit_replay._g_code_think") as mock_think:

        result = behavioral_solve_jaros(
            intent="add foo",
            name="foo",
            current_src=None,
            context="",
            pkg="pkg",
            runtime=rt,
            llm=_FakeLlm(),
            spec_path=spec_p,
            test_path=test_p,
            code_path=code_p,
            think=True,
        )

    # No crash, no think (current_src=None -> "" -> no doctest examples)
    assert mock_think.call_count == 0
    assert isinstance(result, dict)
    assert "code" in result
