"""Offline tests for EXT-020 harness/decomp_probe.py.

All tests run without the Jetson (no LLM, no Docker). Plan generation,
implementation, and the hidden oracle are replaced by stubs. The repo is a
minimal temp directory.

Verified with:
    python -m pytest tests/test_decomp_probe.py -v
"""
from __future__ import annotations

import ast
import tempfile
from pathlib import Path


# ---------------------------------------------------------------------------
# Syntax + import smoke-test
# ---------------------------------------------------------------------------

def test_decomp_probe_parses():
    """decomp_probe.py must parse without syntax errors."""
    src = (Path(__file__).resolve().parents[1] / "harness" / "decomp_probe.py").read_text(
        encoding="utf-8"
    )
    ast.parse(src)  # raises SyntaxError on failure


def test_decomp_probe_imports():
    """Top-level symbols are importable (no heavy LLM imports at module scope)."""
    from harness.decomp_probe import (  # noqa: F401
        _g_plan,
        _g_code_from_plan,
        _core_decomp_probe,
        probe_task_decomp,
        run_decomp_probe,
    )


# ---------------------------------------------------------------------------
# Helpers shared across tests
# ---------------------------------------------------------------------------

def _make_repo_and_task(tmpdir: Path):
    """Create a minimal repo structure and task dict for offline testing."""
    (tmpdir / "pkg").mkdir(exist_ok=True)
    cf = "pkg/mod.py"
    (tmpdir / cf).write_text("def foo():\n    pass\n", encoding="utf-8")
    task = {
        "sha": "abc12345" * 5,
        "parent": "p" * 40,
        "subject": "add foo behaviour",
        "redgreen": ["tests/test_mod.py::test_foo"],
        "code_files": [cf],
        "test_files": ["tests/test_mod.py"],
        "repo": "pkg",
    }
    targets = [(cf, "foo", "def foo():\n    pass\n")]
    orig = {cf: "def foo():\n    pass\n"}
    gherkins = {(cf, "foo"): "Given foo called\nThen it returns None"}
    return task, targets, orig, gherkins


def _make_stub_oracle(pass_greedy: bool = False, pass_decomp: bool = True):
    """Return a stub oracle.

    Call index 0 is the greedy (no-plan) baseline; index 1 is the decomp attempt.
    This matches the order in _core_decomp_probe (greedy first, decomp second).
    """
    call_count: list[int] = [0]

    def oracle(repo, nodes, timeout):
        idx = call_count[0]
        call_count[0] += 1
        if idx == 0:
            return set() if pass_greedy else set(nodes)
        else:
            return set() if pass_decomp else set(nodes)

    oracle.call_count = call_count
    return oracle


# ---------------------------------------------------------------------------
# _core_decomp_probe — plan is fed into implement_fn
# ---------------------------------------------------------------------------

def test_core_decomp_plan_passed_to_implement():
    """The plan generated by plan_fn must be passed as the last arg to implement_fn.

    - implement_fn is called twice: once for greedy (empty plan '') and once for
      decomp (with the plan from plan_fn).
    - plan_fn is called exactly once (for the decomp path only).
    """
    from harness.decomp_probe import _core_decomp_probe

    plan_calls: list[tuple] = []
    impl_plan_args: list[str] = []

    def stub_plan_fn(subject, name, parent_src, context, gherkin):
        plan = f"1. parse args\n2. iterate\n3. return result for {name}"
        plan_calls.append((subject, name))
        return plan

    def stub_implement_fn(subject, name, parent_src, context, gherkin, plan):
        impl_plan_args.append(plan)
        return f"def {name}():\n    pass\n"

    stub_oracle = _make_stub_oracle(pass_greedy=False, pass_decomp=True)

    with tempfile.TemporaryDirectory() as tmpdir:
        repo = Path(tmpdir)
        task, targets, orig, gherkins = _make_repo_and_task(repo)

        result = _core_decomp_probe(
            targets=targets,
            orig=orig,
            gherkins=gherkins,
            task=task,
            repo=repo,
            timeout=10,
            plan_fn=stub_plan_fn,
            implement_fn=stub_implement_fn,
            oracle_fn=stub_oracle,
        )

    # plan_fn called once (decomp path only, not greedy)
    assert len(plan_calls) == 1, f"expected 1 plan call, got {len(plan_calls)}"

    # implement_fn called twice: greedy (empty plan) + decomp (real plan)
    assert len(impl_plan_args) == 2, f"expected 2 implement calls, got {len(impl_plan_args)}"
    assert impl_plan_args[0] == "", "greedy call must pass empty plan"
    assert "parse args" in impl_plan_args[1], "decomp call must pass the plan text"

    # Scoring
    assert result["greedy_pass"] is False
    assert result["decomp_pass"] is True
    assert "skipped" not in result or result.get("skipped") is False


def test_core_decomp_oracle_is_score_only():
    """Oracle output must NOT influence plan_fn or implement_fn inputs.

    We verify by recording all plan_fn and implement_fn argument tuples and
    confirming none of them vary based on oracle outcomes.  An alternating oracle
    is used so any leakage would produce different args on different calls.
    """
    from harness.decomp_probe import _core_decomp_probe

    plan_args: list[tuple] = []
    impl_args: list[tuple] = []

    def recording_plan_fn(subject, name, parent_src, context, gherkin):
        plan_args.append((subject, name, gherkin))
        return "1. plan step"

    def recording_impl_fn(subject, name, parent_src, context, gherkin, plan):
        impl_args.append((subject, name, gherkin, plan))
        return f"def {name}():\n    pass\n"

    call_count: list[int] = [0]

    def alternating_oracle(repo, nodes, timeout):
        idx = call_count[0]
        call_count[0] += 1
        return set() if idx % 2 == 0 else set(nodes)

    with tempfile.TemporaryDirectory() as tmpdir:
        repo = Path(tmpdir)
        task, targets, orig, gherkins = _make_repo_and_task(repo)

        _core_decomp_probe(
            targets=targets,
            orig=orig,
            gherkins=gherkins,
            task=task,
            repo=repo,
            timeout=10,
            plan_fn=recording_plan_fn,
            implement_fn=recording_impl_fn,
            oracle_fn=alternating_oracle,
        )

    # plan_fn called once only (decomp, not greedy)
    assert len(plan_args) == 1

    # implement_fn called twice: greedy + decomp
    assert len(impl_args) == 2

    # subject, name, gherkin must be identical across both implement calls
    assert impl_args[0][0] == impl_args[1][0], "subject must be identical"
    assert impl_args[0][1] == impl_args[1][1], "name must be identical"
    assert impl_args[0][2] == impl_args[1][2], "gherkin must be identical (oracle must not feed back)"


def test_core_decomp_none_pass():
    """When oracle never passes, both greedy_pass=False and decomp_pass=False."""
    from harness.decomp_probe import _core_decomp_probe

    stub_oracle = _make_stub_oracle(pass_greedy=False, pass_decomp=False)

    with tempfile.TemporaryDirectory() as tmpdir:
        repo = Path(tmpdir)
        task, targets, orig, gherkins = _make_repo_and_task(repo)

        result = _core_decomp_probe(
            targets=targets,
            orig=orig,
            gherkins=gherkins,
            task=task,
            repo=repo,
            timeout=10,
            plan_fn=lambda *_: "1. parse\n2. return",
            implement_fn=lambda *_a: f"def foo():\n    pass\n",
            oracle_fn=stub_oracle,
        )

    assert result["decomp_pass"] is False
    assert result["greedy_pass"] is False


def test_core_decomp_greedy_passes_decomp_fails():
    """Correctly reports when greedy passes but decomp fails (unusual but possible)."""
    from harness.decomp_probe import _core_decomp_probe

    stub_oracle = _make_stub_oracle(pass_greedy=True, pass_decomp=False)

    with tempfile.TemporaryDirectory() as tmpdir:
        repo = Path(tmpdir)
        task, targets, orig, gherkins = _make_repo_and_task(repo)

        result = _core_decomp_probe(
            targets=targets,
            orig=orig,
            gherkins=gherkins,
            task=task,
            repo=repo,
            timeout=10,
            plan_fn=lambda *_: "1. plan",
            implement_fn=lambda s, n, *_: f"def {n}():\n    pass\n",
            oracle_fn=stub_oracle,
        )

    assert result["greedy_pass"] is True
    assert result["decomp_pass"] is False


def test_core_decomp_per_target_populated():
    """per_target list contains name, plan, and code for each target function."""
    from harness.decomp_probe import _core_decomp_probe

    stub_oracle = _make_stub_oracle(pass_decomp=True)

    with tempfile.TemporaryDirectory() as tmpdir:
        repo = Path(tmpdir)
        task, targets, orig, gherkins = _make_repo_and_task(repo)

        result = _core_decomp_probe(
            targets=targets,
            orig=orig,
            gherkins=gherkins,
            task=task,
            repo=repo,
            timeout=10,
            plan_fn=lambda subject, name, *_: f"1. parse\n2. return for {name}",
            implement_fn=lambda subject, name, *_: f"def {name}():\n    return None\n",
            oracle_fn=stub_oracle,
        )

    assert len(result["per_target"]) == 1
    pt = result["per_target"][0]
    assert pt["name"] == "foo"
    assert "1. parse" in pt["plan"]
    assert "def foo" in pt["code"]


def test_core_decomp_files_restored_after_probe():
    """Repo files must be restored to their original content after the probe completes."""
    from harness.decomp_probe import _core_decomp_probe

    stub_oracle = _make_stub_oracle(pass_decomp=True)

    with tempfile.TemporaryDirectory() as tmpdir:
        repo = Path(tmpdir)
        task, targets, orig, gherkins = _make_repo_and_task(repo)

        original_content = orig["pkg/mod.py"]

        _core_decomp_probe(
            targets=targets,
            orig=orig,
            gherkins=gherkins,
            task=task,
            repo=repo,
            timeout=10,
            plan_fn=lambda *_: "1. plan",
            implement_fn=lambda s, n, *_: f"def {n}():\n    return 42\n",
            oracle_fn=stub_oracle,
        )

        restored = (repo / "pkg/mod.py").read_text(encoding="utf-8")
        assert restored == original_content, "repo file must be restored after probe completes"


def test_core_decomp_files_restored_after_probe_fail():
    """Repo files are restored even when neither attempt passes (oracle always fails)."""
    from harness.decomp_probe import _core_decomp_probe

    stub_oracle = _make_stub_oracle(pass_greedy=False, pass_decomp=False)

    with tempfile.TemporaryDirectory() as tmpdir:
        repo = Path(tmpdir)
        task, targets, orig, gherkins = _make_repo_and_task(repo)
        original_content = orig["pkg/mod.py"]

        _core_decomp_probe(
            targets=targets,
            orig=orig,
            gherkins=gherkins,
            task=task,
            repo=repo,
            timeout=10,
            plan_fn=lambda *_: "1. plan",
            implement_fn=lambda s, n, *_: f"def {n}():\n    return None\n",
            oracle_fn=stub_oracle,
        )

        restored = (repo / "pkg/mod.py").read_text(encoding="utf-8")
        assert restored == original_content, "repo file must be restored even when probe fails"


def test_core_decomp_oracle_call_order():
    """Oracle is called exactly twice: first for greedy, then for decomp."""
    from harness.decomp_probe import _core_decomp_probe

    oracle_call_args: list[tuple] = []

    def recording_oracle(repo, nodes, timeout):
        oracle_call_args.append((list(nodes), timeout))
        return set(nodes)  # always fail

    with tempfile.TemporaryDirectory() as tmpdir:
        repo = Path(tmpdir)
        task, targets, orig, gherkins = _make_repo_and_task(repo)

        _core_decomp_probe(
            targets=targets,
            orig=orig,
            gherkins=gherkins,
            task=task,
            repo=repo,
            timeout=10,
            plan_fn=lambda *_: "1. plan",
            implement_fn=lambda s, n, *_: f"def {n}():\n    pass\n",
            oracle_fn=recording_oracle,
        )

    # Oracle must be called exactly twice: greedy + decomp
    assert len(oracle_call_args) == 2, f"expected 2 oracle calls, got {len(oracle_call_args)}"
    # Both calls use the same redgreen nodes
    assert oracle_call_args[0][0] == oracle_call_args[1][0], "both calls use the same nodes"
