"""Generate docs/CATALOG.md from the live agents / tools / evals.

Keeps the written-up catalog honest and current: it reads the actual files, so it can
never drift from reality. Run it (or let the supervisor run it) after adding/removing
agents, tools, or eval tasks.
"""

from __future__ import annotations

import ast
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AGENTS = ROOT / ".jaros-data" / "agents"
TOOLS = ROOT / ".jaros-data" / "tools"
EVALS = ROOT / "evals" / "coding_tasks"
OUT = ROOT / "docs" / "CATALOG.md"


def _module_doc(path: Path) -> str:
    try:
        doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or ""
        return doc.strip().splitlines()[0] if doc.strip() else ""
    except Exception:
        return ""


def _name_attr(path: Path) -> str:
    m = re.search(r'^NAME\s*=\s*["\'](.+?)["\']', path.read_text(encoding="utf-8"), re.M)
    if m:
        return m.group(1)
    m = re.search(r'\bNAME\s*=\s*["\'](.+?)["\']', path.read_text(encoding="utf-8"))
    return m.group(1) if m else path.stem


def _rows(directory: Path) -> list[tuple[str, str]]:
    rows = []
    for p in sorted(directory.glob("*.py")):
        if p.name.startswith("_"):
            continue
        rows.append((_name_attr(p), _module_doc(p)))
    return rows


def main() -> None:
    agents = _rows(AGENTS)
    tools = _rows(TOOLS)
    evals = []
    for p in sorted(EVALS.glob("*.json")):
        d = json.loads(p.read_text(encoding="utf-8"))
        instr = (d.get("instruction", "").split(".")[0])[:80]
        evals.append((d.get("id"), d.get("tier", 1), instr))

    lines = ["# jaros-code — Live Catalog",
             "",
             "_Auto-generated by `scripts/gen_catalog.py` from the actual agents/tools/evals._",
             f"_Counts: **{len(agents)} agents · {len(tools)} tools · {len(evals)} evals**._",
             "",
             "## Agents (single-purpose reasoning, gemma2:2b)", ""]
    for name, doc in agents:
        lines.append(f"- **`{name}`** — {doc}")
    lines += ["", "## Tools (deterministic execution plane)", ""]
    for name, doc in tools:
        lines.append(f"- **`{name}`** — {doc}")
    lines += ["", "## Eval tasks (by tier)", ""]
    for tier in sorted({e[1] for e in evals}):
        lines.append(f"### Tier {tier}")
        for eid, t, instr in evals:
            if t == tier:
                lines.append(f"- **{eid}** — {instr}")
        lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(agents)} agents, {len(tools)} tools, {len(evals)} evals)")


if __name__ == "__main__":
    main()
